done with the landing page of component UI
ajit-sharmaGH/Tungsten-UI pull request #1
Opened 2022-01-30 19:40 UTC by ajit-sharmaGH

2022-01-30 20:45 UTC, krishnakant01 commented
Hey, I have gone through your code. It looks good to merge.

2022-02-01 18:16 UTC, Mohasin-Haque requested changes
Your code is good but needs some changes as commented.. please go through your files once.

2022-02-01 18:16 UTC, Mohasin-Haque commented on CSS/base/color.css
> +    --green: green;
You can use purpose here.. if you have to use the name of color then you can do it directly..

2022-02-01 18:16 UTC, Mohasin-Haque commented on CSS/base/nav.css
> +    /* min-height: 8vh; */
remove the commented part

2022-02-01 18:16 UTC, Mohasin-Haque commented on CSS/base/nav.css
> +        position: absolute;
Use media queries at last of the page.

2022-02-01 18:16 UTC, Mohasin-Haque commented on CSS/base/nav.css
> +        justify-content: center;
you can make a separate class for flex instead of using it again and again.

2022-02-01 18:16 UTC, Mohasin-Haque commented on CSS/base/reset.css
> +
please run prettier and also do take care of the indentation.

2022-02-01 18:16 UTC, Mohasin-Haque commented on Htmlfiles/documentation.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
you can add more meta description to personalise the ui.

2022-02-01 18:16 UTC, Mohasin-Haque commented on Htmlfiles/documentation.html
> +
why gap?

2022-02-01 18:16 UTC, Mohasin-Haque commented on Htmlfiles/install.html
> +        <div class="logo">
formate the file

2022-02-01 18:16 UTC, Mohasin-Haque commented on style.css
> +@import url("CSS/base/nav.css");
you can add comments to sanity

2022-02-02 17:02 UTC, ajit-sharmaGH commented on Htmlfiles/install.html
> +        <div class="logo">
Okk will do that

2022-02-02 17:02 UTC, merged