Alert button
ajit-sharmaGH/Tungsten-UI pull request #5
Opened 2022-02-03 17:19 UTC by ajit-sharmaGH

2022-02-03 18:17 UTC, Namrata-J commented on CSS/alert.css
> +    /* background-color: var(--background-color); */
remove this commented properties if possible!!

2022-02-03 18:17 UTC, Namrata-J commented on CSS/base/reset.css
> +    /* margin: 0rem; */
here as well

2022-02-03 18:58 UTC, ajit-sharmaGH commented on CSS/alert.css
> +    /* background-color: var(--background-color); */
Okk will do that

2022-02-04 04:36 UTC, JantuDeb commented
> _No description provided._

Please add PR description

2022-02-04 04:40 UTC, JantuDeb requested changes
Suggested some changes

2022-02-04 04:40 UTC, JantuDeb commented on CSS/alert.css
> +}
`.alert-btn-all` can be reduced to `.alert-btn`

2022-02-05 02:56 UTC, Raghav888 approved these changes
Approved

2022-02-05 18:58 UTC, merged