merged all html files into the doc file and deleted unwanted html files
ajit-sharmaGH/Tungsten-UI pull request #9
Opened 2022-02-08 21:09 UTC by ajit-sharmaGH

2022-02-09 21:15 UTC, harshitadaswani requested changes
- use shorthand properties
- don't use `!important` in CL
- and try to make different PRs as it is difficult to review so many files together

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/avatar.css
> +
remove empty space

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/avatar.css
> +    /* background-image: url("../images/tungsten3.jpg"); */
remove unnecessary comments

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/base/nav.css
> +    padding: 0.3rem 0.6rem 0.3rem 0.6rem;
use shorthand property `padding: 0.3rem 0.6rem`

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/base/reset.css
>      margin: 1rem 0rem 1rem 0rem;
use shorthand property

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/base/reset.css
>      padding: 0.5rem 1rem 0.5rem 1rem;
again shorthand property

2022-02-09 21:15 UTC, harshitadaswani commented on CSS/base/reset.css
> +    max-height: 40vh !important;
don't use `!important` in component library

2022-02-09 21:15 UTC, harshitadaswani commented on main/doc.css
> +    padding: 0.5rem 2rem 0.5rem 2rem;
shorthand property

2022-02-09 21:15 UTC, harshitadaswani commented on main/doc.css
> +    align-items: center; */
remove comments

2022-02-10 02:07 UTC, JantuDeb approved these changes
Implement the changes @harshitadaswani pointed out other than that everything is fine

2022-02-10 07:50 UTC, merged